apiVersion: 1

datasources:
  - name: ClickHouse Cluster (via HAProxy)
    type: vertamedia-clickhouse-datasource
    access: proxy
    url: http://clickhouse-haproxy:8124
    basicAuth: false
    isDefault: true
    jsonData:
      defaultDatabase: default
      port: 8124
      server: clickhouse-haproxy
      username: default
      secure: false
      timeout: 30
      addCorsHeader: true
    secureJsonData:
      password: default
    editable: true

